### Create product
POST http://localhost:8000/api/v1/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "A cheap product",
  "price": 1
}

### List products
GET http://localhost:8000/api/v1/products HTTP/1.1
Authorization: Bearer {{access_token}}

### Get one product
GET http://localhost:8000/api/v1/products/c55d1e71-c862-4300-ba76-ed89667c63d5 HTTP/1.1
Authorization: Bearer {{access_token}}

### Update a product
PUT http://localhost:8000/api/v1/products/c55d1e71-c862-4300-ba76-ed89667c63d5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "A real expensive product",
  "price": 9999.9
}

### Delete a product
DELETE http://localhost:8000/api/v1/products/c55d1e71-c862-4300-ba76-ed89667c63d5 HTTP/1.1
Authorization: Bearer {{access_token}}